theme: jekyll-theme-architect

plugins:
  - jekyll-seo-tag

title: Fast Json processing
description: SpeeJson is a extreme high throughput java library for Json serialization and deserialization
image: https://heitorfm.github.io/speejson/img/clock.png
