theme: jekyll-theme-architect

plugins:
  - jekyll-seo-tag

image: /img/banner.png
title: Fast Json processing
description: SpeeJson is a extreme high throughput java library for Json serialization and deserialization

defaults:
  - scope:
      path: ""
    values:
      image: /img/banner.png
